### ISSUE TITLE
Is it possible to generate the GIF as a base64 file?

### ISSUE THREAD

**Issue by slidenerd** [eugeneware/gifencoder#14]
I would like to generate the image as a base 64 string instead of storing it in a file? What would be the right way to do it?

**Comment by Wodki** [comment]
What do you mean, btw in your title you say _generate the GIF as a base64 file_ while in your comment, _ to generate the image as a base 64 string_, I dont understand. Do you just want to get the image's basse64 data?

**Comment by slidenerd** [comment]
Yes i am looking to just get the image's data, sorry about the ambiguity

**Comment by Wodki** [comment]
If you are looking to get the base64 data (not the grb or rgba, which is what you might actually want to add the data to the gif) you can just do.

```js
var your_image = new Canvas(10, 10)
your_image .src = 'data:image/jpeg;base64,'+ data.toString('base64');```

**Comment by heikkipora** [comment]
@slidenerd Did the latest answer satisfy you or are you still looking for a solution? Please provide a more detailed description of what you want to achieve if the question is still in the open.

**Comment by heikkipora** [comment]
Closing as inactive

**Comment by conniekim** [comment]
Is there a way to get the gif's base64 data?

**Comment by heikkipora** [comment]
Just pipe the output to a stream that generates base64 from binary data - such as this one: https://www.npmjs.com/package/base64-stream
