### ISSUE TITLE
Garbled gif

### ISSUE THREAD

**Issue by mhjb** [eugeneware/gifencoder#15]
Hi there

The below (coffeescript)… 

```
GIFEncoder = require 'gifencoder'
fs = require 'fs'
pngFileStream = require 'png-file-stream'

encoder = new GIFEncoder 1450, 1150

pngFileStream './img/*.png'
	.pipe encoder.createWriteStream
		repeat: -1
		delay: 200
		quality: 8
	.pipe fs.createWriteStream 'test.gif'
```

… produces this garbled animated gif …

![test](https://cloud.githubusercontent.com/assets/1380991/24018499/fe9430dc-0af8-11e7-80ae-b711b4f17c65.gif)

… from a folder of pngs like this:

![metservice-wellington tue feb 07 2017 16 08 24 gmt 1300 nzdt](https://cloud.githubusercontent.com/assets/1380991/24018588/607b1c52-0af9-11e7-819f-cba728428954.png)

Any ideas? 

Thanks for your time
Matthew

**Comment by Wodki** [comment]
@mhjb I am not familiar with coffescript but if I had to guess, you are need to give RGBA data while you are giving RGB, check canvas getImagedata() method perhaps

**Comment by mhjb** [comment]
Thanks very much; I'll have a play.

**Comment by mhjb** [comment]
[png-file-stream](https://github.com/eugeneware/png-file-stream) apparently emits RGBA…

Here's the Javascript, by the way:

```
var GIFEncoder = require('gifencoder');
var fs = require('fs');
var pngFileStream = require('png-file-stream');

var encoder = new GIFEncoder(1450, 1150);

pngFileStream('./img/2017-03-16*.png', false).pipe(encoder.createWriteStream({
  repeat: -1,
  delay: 500,
  quality: 10
})).pipe(fs.createWriteStream('test.gif'));
```

**Comment by eerwitt** [comment]
Could it be that the `width` and `height` parameter of `GIFEncoder` must be the same size as the PNG images being streamed in?

It seems like all the logic is based off using a 1-dimensional array. If the input image data is not the exact same size as the `width` and `height` parameter, the images would likely be corrupted. The corrupted images you've highlighted look like parts of the original image skewed in color.

See: https://github.com/eugeneware/gifencoder/blob/97745823a816dd479c2e890949fe406d67ea1b94/lib/GIFEncoder.js#L322

**Comment by heikkipora** [comment]
It looks like the last comment solved the problem, closing.

**Comment by LoganArnett** [comment]
I am also having this issue and I have the width and height matching the resulting photos perfectly, basically I am creating images with JIMP and then trying to use those images in a gif right after. I have also tried using a setTimeout incase the image are not available yet but that still returned a gif with this appearance:

![image](http://cloud.loganarnett.com/3Q3m2m3V0k2h/Screen%20Recording%202017-12-04%20at%2005.35%20PM.gif)

My current code is:
```js
const Jimp = require("jimp");
const GIFEncoder = require('gifencoder');
const pngFileStream = require('png-file-stream');
const Promise = require('bluebird');
const fs = require('fs');
const encoder = new GIFEncoder(600, 338);

return Promise.all([
    Jimp.read('./assets/background.png'),
    Jimp.read('./assets/helmet.png')
])
.spread((bg, helmet) => {
    return Promise.all([
        bg.clone().composite(helmet, 200, 100).write('images/first.png'),
        bg.clone().composite(helmet.clone().rotate(5, false), 200, 100).rgba(true).write('images/second.png'),
        bg.clone().composite(helmet.clone().rotate(15, false), 200, 100).rgba(true).write('images/third.png'),
        bg.clone().composite(helmet.clone().rotate(5, false), 200, 100).rgba(true).write('images/fourth.png'),
        bg.clone().composite(helmet.clone().rotate(0, false), 200, 100).rgba(true).write('images/fifth.png'),
        bg.clone().composite(helmet.clone().rotate(-5, false), 200, 100).rgba(true).write('images/sixth.png'),
        bg.clone().composite(helmet.clone().rotate(-15, false), 200, 100).rgba(true).write('images/seventh.png')
    ]);
})
.then(() => {
     pngFileStream('images/*.png', false)
        .pipe(encoder.createWriteStream({ repeat: -1, delay: 500, quality: 10}))
        .pipe(fs.createWriteStream('helmet.gif'));
})
```

**Comment by heikkipora** [comment]
@LoganArnett your code has two issues:
 * jimp's write() method does not return a promise (which is really odd: https://github.com/oliver-moran/jimp/issues/374) - so the images have not been generated yet when the next .then() block is executed
 * you pass '''false''' as the second parameter to pngFileStream() which essentially tells it to skip PNG decoding. remove that parameter

**Comment by LoganArnett** [comment]
Interesting, I did not realize that Jimps write didnt return a promise,  thanks for the info @heikkipora I will test these changes today
