### ISSUE TITLE
Is it possible to add images as frames?

### ISSUE THREAD

**Issue by matty22** [eugeneware/gifencoder#17]
I'm trying to create an animated gif using GifEncoder, but rather than using fillRect or fillStyle, etc. I am trying to do something like:

```
// Create canvas image element
let image = new Image();

// Set its source to the path of an image file stored on my local server
image.src = '../public/images/image1.png';
      
// Encode frame to gif
encoder.addFrame(image);
```

I end up getting a 500 internal server error and the 'gif' that gets created and dumped into a temporary file on my server is text that looks something like this string: `GIF89a`

The README file does not mention anything about using images or examples of how to do that, but I see lots of mention in other issues about something called 'png-file-stream'. Is that package required to process images with GifEncoder?

**Comment by heikkipora** [comment]
GIFEncoder only deals with raw pixel data, so for using compressed image files such as PNGs you need to use an external library like ```png-file-stream``` as you correctly assumed.
The **Streaming API - Duplex Piping with Writes** is the one example you need to look at.
