### ISSUE TITLE
How to use with jpg or png array ?

### ISSUE THREAD

**Issue by userbq201** [eugeneware/gifencoder#19]
Please, help. How to convert an array of images into a hypha? And is it possible for everyone to set the time? If not, then there is something like that?

**Comment by heikkipora** [comment]
The pixel stream (from e.g. PNG and JPG) API doesn't support defining delay for individual frames. You need to use the addFrame(context) API for that.
Please study the examples at https://github.com/eugeneware/gifencoder.
