### ISSUE TITLE
Trying to create from array of Buffers results in segmentation fault

### ISSUE THREAD

**Issue by cylinderStudio** [eugeneware/gifencoder#2]
I have an array of Buffers and when I try to create an animated GIF, I get 

```
Segmentation fault: 11
```

My code for creating GIF:

```
var encoder = new GIFEncoder(640,640);
encoder.createReadStream().pipe(fs.createWriteStream('myAnimatedGif.gif));
encoder.start();
.setRepeat(0);
.setDelay(500);

for (var i=0; i<frame_buffers.length; i++) {
    encoder.addFrame(frame_buffers[i]);
}

encoder.finish();
```

It does attempt to write the file, but it's normally 0 bytes, occasionally writing out 6 or 7 bytes of data and still corrupt.

**Comment by eugeneware** [comment]
The buffers need to be a Buffer or UIntArray or RGB pixels, Is it possible that you have included an alpha channel as well? So the total length of the buffer would be (w*h*3).

**Comment by heikkipora** [comment]
Is this issue still relevant to you @cylinderStudio ?  If so, please could you provide a Minimal Working Example to reproduce it ?

**Comment by heikkipora** [comment]
Closing as inactive
