### ISSUE TITLE
Using Gifencoder inside of Lambda Function

### ISSUE THREAD

**Issue by LoganArnett** [eugeneware/gifencoder#20]
Curious to see if anyone has been able to implement this. Currently I have a setup that works on the first gif encoding but it fails after that every single time. Not sure if this is a Lambda issue or a Gifencoder issue.

Any help would be greatly appreciated

**Comment by heikkipora** [comment]
Would you like to post a code + configuration sample?

**Comment by msholty-fd** [comment]
@LoganArnett I just got this working on Amazon Lambda. I essentially used the code in https://github.com/Nooshu/node-countdown-gif, but had to make sure I built it within a docker image that simulates an ec2 environment (or just ssh into an ec2 instance to build). I had to mess with the code in the repo a bit to make this work, something along the lines of:

```
exports.handler = (event, context) => {
  const CountdownGenerator = require('./countdown-generator');
  let { time, width, height, color, bg, frames } = event.queryStringParameters;

  if(!time){
      throw Error('Time parameter is required.');
  }

  CountdownGenerator.init(time, width, height, color, bg, frames, (body) => {
    context.done(null, {
        statusCode: 200,
        headers: {
          'Content-Type': 'image/gif',
          'Content-Length': body.length,
          'Accept-Ranges': 'bytes',
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': '*',
          'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key',
        },
        body: body.toString('base64'),
        isBase64Encoded: true,
    });
  });
};
```
