### ISSUE TITLE
Possible to use addFrame with base46 data instead of imageData? 

### ISSUE THREAD

**Issue by nicolasdelfino** [eugeneware/gifencoder#21]
Hi! I'm searching for something that would allow me to generate an animated GIF from an array of base64 strings, is this possible and implemented / possible but not implemented / impossible? 
Also, does this need the browser to work or will it work in window less environments? thanks!

**Comment by heikkipora** [comment]
gifencoder's streaming API works with raw pixels in 32bit RGBA format and the addFrame() API works with a canvas context. So you need to decode whatever you have in your base64 encoded frames first. It works just fine without a browser, and I personally prefer using it on server-side.
