### ISSUE TITLE
Animated gif is very low quality even at highest quality setting

### ISSUE THREAD

**Issue by tjpc3** [eugeneware/gifencoder#24]
Hello! I'm trying to generate a gif using three frames that I have loaded in as Sharp js objects.
Here is my code:
```
async function createGIF(stitchedTextFrames) {
    let encoder = new GIFEncoder(stitchedTextFrames[0].info.width, stitchedTextFrames[0].info.height);

    encoder.start();
    encoder.setRepeat(0);
    encoder.setDelay(166); // 10 frames at 60 fps
    encoder.setQuality(10);

    for (var i in stitchedTextFrames) {
        encoder.addFrame(stitchedTextFrames[i].data);
    }

    encoder.finish();

    return encoder.out.getData();
}
```
The objects in stitchedTextFrames are created by calling `.raw().toBuffer({resolveWithObject: true})` on 3 different Sharp objects. The output gif and input buffers are in this imgur album: [https://imgur.com/a/6TwW6](https://imgur.com/a/6TwW6)

I'm using node v8.0.0 on npm v5.7.1

**Comment by heikkipora** [comment]
It seems that your source images already have some "extra pixels" around the shapes. See this screenshot taken from Photoshop (with one of your source images): https://imgur.com/a/WnYBD
