### ISSUE TITLE
incorrect generating gif when using sharp

### ISSUE THREAD

**Issue by hbakhtiyor** [eugeneware/gifencoder#26]
the sample code

```js
const fs = require('fs');
const sharp = require('sharp');
const GIFEncoder = require('gifencoder');

(async () => {
  const image = await sharp('thumbs.jpeg').raw().toBuffer({resolveWithObject: true});

  const encoder = new GIFEncoder(image.info.width, image.info.height);
  
  encoder.createReadStream().pipe(fs.createWriteStream('thumbs.gif'));
  
  encoder.start();
  encoder.setRepeat(-1);   
  encoder.setDelay(500);  
  encoder.setQuality(100);   

  encoder.addFrame(image.data);
  encoder.finish();
})()

```

the jpeg input and gif result.
![thumbs](https://user-images.githubusercontent.com/3434496/38941354-d1850b6c-4345-11e8-913f-75acac2b0cb6.gif)
![thumbs](https://user-images.githubusercontent.com/3434496/38941357-d232b8a2-4345-11e8-985e-063e4cf803e1.jpeg)

**Comment by heikkipora** [comment]
addFrame() expects the data to be in RGBA layout (4 bytes per pixel). I assume sharp's .raw() produces 3 bytes per pixels by default. Are there options in sharp to change that to 4 bytes per pixel?

**Comment by heikkipora** [comment]
I took a look at the issue you referenced only now - do I read that correctly that you tried four channels already but had no luck?

**Comment by hbakhtiyor** [comment]
just used the `.joinChannel(Buffer.alloc(width * height, 255), { raw: { channels: 1, width, height} })` workaround and works well

```js
```js
const fs = require('fs');
const sharp = require('sharp');
const GIFEncoder = require('gifencoder');

(async () => {
  const width = 1200, height = 630;
  const imageData = await sharp('thumbs.jpeg')
  .joinChannel(Buffer.alloc(width * height, 255), { raw: { channels: 1, width, height} })
  .raw().toBuffer();

  const encoder = new GIFEncoder(width, height);
  
  encoder.createReadStream().pipe(fs.createWriteStream('thumbs.gif'));
  
  encoder.start();
  encoder.setRepeat(-1);   
  encoder.setDelay(500);  
  encoder.setQuality(100);   

  encoder.addFrame(imageData);
  encoder.finish();
})()
```

```

**Comment by heikkipora** [comment]
Good to hear that!

**Comment by hbakhtiyor** [comment]
generating a bit blur image than original

**Comment by elemarin** [comment]
Hi, I came across a similar issue, and tried the suggested workaround, but this caused the image to look different than expected when resizing.

here's how it looked with the workaround:

![gitExample](https://user-images.githubusercontent.com/987341/67886920-f3826100-fb0f-11e9-8a53-5b7d93c04925.gif)

after investigating, it seems like there is a simpler way to add the missing channel when using Sharp's `raw()`

here's the code I used 

```
const fs = require('fs');
const sharp = require('sharp');
const GIFEncoder = require('gifencoder');

(async () => {

    let transform = sharp('imagen.jpg');

    transform.resize(200, 800, {
        fit: 'contain',
        background: {
            r: 255,
            g: 255,
            b: 255,
            alpha: 1
        }
    });

    transform.ensureAlpha();

    transform.raw();

    let buffer = await transform.toBuffer();


    const encoder = new GIFEncoder(200, 800);

    encoder.createReadStream().pipe(fs.createWriteStream('gitExample.gif'));

    encoder.start();
    encoder.addFrame(buffer);
    encoder.finish();
})()
```

and the image that this produces:

![gitExample](https://user-images.githubusercontent.com/987341/67886967-0a28b800-fb10-11e9-8457-8ec2ff761c41.gif)
