### ISSUE TITLE
can't recreate two gif

### ISSUE THREAD

**Issue by Ants-double** [eugeneware/gifencoder#31]
` pngFileStream(strPath + '/temp/*.png')
                        .pipe(encoder.createWriteStream({
                            repeat: -1,
                            delay: 500,
                            quality: 10
                        }))
                        .pipe(fs.createWriteStream(gifName)).on('finish', (res) => {
                            console.log(res);
                            gifObject.emit('Gif_event', "ok");
                        });`
first is ok ,but the second isn't work .Thank you

**Comment by heikkipora** [comment]
Please be a bit more specific; what is ok and what doesn't work?

**Comment by heikkipora** [comment]
Closed as inactive
