### ISSUE TITLE
Unexpected final result

### ISSUE THREAD

**Issue by djagiello** [eugeneware/gifencoder#32]
My first quality problem was the wrongly set resolution of the output image which resulted in such quality:
![image](https://user-images.githubusercontent.com/38032481/41136033-a286e6f8-6ad4-11e8-9fd3-fcbcf4e44a4a.png)
After setting the resolution, the picture has definitely returned to a more mundane look:
![image](https://user-images.githubusercontent.com/38032481/41136066-d5bbc066-6ad4-11e8-9bfe-081375ce7f41.png)

Unfortunately, I encountered another problem related to the final result. I have pictures in 8 bit colors, and the output gif has 24 bit colors.
This affects the quality of the original image terribly. How can you set the number of colors to 8 bits?

My code:
```var GIFEncoder = require('gifencoder');
var encoder = new GIFEncoder(544, 315);
var pngFileStream = require('png-file-stream');
var fs = require('fs');

pngFileStream('slides/tmp_?.png')
    .pipe(encoder.createWriteStream({ repeat: -1, delay: 500, quality: 10 }))
    .pipe(fs.createWriteStream('myanimated.gif'));
```

My git repository with graphic and code: https://github.com/djagiello/gifgen

**Comment by heikkipora** [comment]
Would it be possible for you to use 24bit PNGs as the source images ? I don't think gifencoder handles 8bit source images too well.

btw. the gif file format has a maximum of 256 entries in the palette, so it's always 8bit / pixel.

**Comment by heikkipora** [comment]
Closed as inactive
