### ISSUE TITLE
How Should I Fix this?

### ISSUE THREAD

**Issue by wtus** [eugeneware/gifencoder#38]
src
![emoji_1545873167024](https://user-images.githubusercontent.com/19467109/50463299-eb283980-09c5-11e9-83e2-345f50dd62e6.png)
out
![emoji_1545879145718](https://user-images.githubusercontent.com/19467109/50463304-f4b1a180-09c5-11e9-8093-041882b6709a.gif)

how do i improve the quality?
![w40 3 51 w8exh 4km77k](https://user-images.githubusercontent.com/19467109/50463426-b4065800-09c6-11e9-9f4d-4e5edd693aff.png)

mycode,is there anything i did wrong?
![image](https://user-images.githubusercontent.com/19467109/50463452-cb454580-09c6-11e9-9297-7ba5d64c81d0.png)
![image](https://user-images.githubusercontent.com/19467109/50463461-d5ffda80-09c6-11e9-9fe8-9aea7c8763f9.png)

**Comment by heikkipora** [comment]
I would just ensure that those problematic pixels are all of the same (background) color, and without alpha channel in the source image.
