### ISSUE TITLE
The callback time after successfully generating GIF is inaccurate

### ISSUE THREAD

**Issue by zhaitianye** [eugeneware/gifencoder#39]
Hi, I have a problem that involves the development of engineering.I am going to make a batch production of GIF images procedures, there are many different types of GIF, each GIF is not the same, the frame number between 10 frames to 300 frames.This is no problem, but I can not ensure that he produced the time, when I received a successful production callback signal, in fact, is not completely generated, he has been living GIF file size changes, waiting for about 10 seconds to a minute appearance (depending on the number of GIF frames at different times) will be generated.This has an impact on my batch generation GIF, how do I change to solve it?

**Comment by heikkipora** [comment]
I assume you are not waiting for the correct event. See the README (specifically this bit: https://github.com/eugeneware/gifencoder/pull/36/commits/f79c7f464d3e44c49631ab4580ac695f2f020e53)
