### ISSUE TITLE
I made a canvas and than generated its gif file, it is creating quality issue, i have already set the quality of encode to 10.

### ISSUE THREAD

**Issue by theumairriaz** [eugeneware/gifencoder#45]
![abc](https://user-images.githubusercontent.com/41395451/74404806-585a9080-4e4d-11ea-98b5-55b6bec765e0.gif)

**Comment by IveHD** [comment]
have you resolved it?

**Comment by theumairriaz** [comment]
Yes, I resolved it by making a larger gif and then resizing it.

**Comment by arbels** [comment]
try inverting the colors (set the background color to white and the text/shapes to black)

**Comment by skeddles** [comment]
10 is not good quality, set it to 1

**Comment by Caesarovich** [comment]
@theumairriaz , I have had issues like this before.

Try disabling anti-aliasing on the Canvas CTX

```js
// Create a 2D canvas
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext('2d');

ctx.antialias = 'none';
```

**Comment by theumairriaz** [comment]
I am closing it because i'm not working it anymore...
