### ISSUE TITLE
Quality of text is quite poor (e.g. no anti-aliasing), and changing quality parameter has no effect

### ISSUE THREAD

**Issue by bitliner** [eugeneware/gifencoder#8]
I am creating a gif with text.

but the text has very pool quality, it looks like anti-aliasing is missing.

How to fix it?

**Comment by jayasurian123** [comment]
I too facing the same issue. Texts looks not so nice when coverts to gif.

**Comment by heikkipora** [comment]
Is this issue still relevant to you @bitliner and @jayasurian123  ? If so, please could you provide a Minimal Working Example to reproduce it ?

**Comment by heikkipora** [comment]
Closing as inactive
